const BASE_URL_DEVELOPMENT = "http://localhost:7171";
const BASE_URL_DOCKER = "http://localhost:7171";
const ENDPOINTS = {
  //POSTS
  GET_ALL_POSTS: "getAllPosts",
  GET_POST_BY_ID: "getPost",
  CREATE_POST: "createPost",
  UPDATE_POST: "updatePost",
  DELETE_POST_BY_ID: "deletePost",
  TOGGLE_POST_HIDDEN: "togglePostVisibility",
  TOGGLE_USER_FOR_POST: "toggleUserForPost",

  //USERS
  GET_ALL_USERS: "getAllUsers",

  //AUTH
  LOGIN: "login",
  REGISTER: "register",
  HUB: "postHub",
};

const developmentEndpoints = {
  //POSTS
  GET_ALL_POSTS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POSTS}`,
  GET_POST_BY_ID: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
  CREATE_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
  UPDATE_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
  DELETE_POST_BY_ID: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`,
  TOGGLE_POST_HIDDEN: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.TOGGLE_POST_HIDDEN}`,
  TOGGLE_USER_FOR_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.TOGGLE_USER_FOR_POST}`,

  //USERS
  GET_ALL_USERS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,

  //AUTH
  LOGIN: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
  REGISTER: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER}`,
  HUB: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.HUB}`,
};

const dockerEndpoints = {
  //POSTS
  GET_ALL_POSTS: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_ALL_POSTS}`,
  GET_POST_BY_ID: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_POST_BY_ID}`,
  CREATE_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.CREATE_POST}`,
  UPDATE_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.UPDATE_POST}`,
  DELETE_POST_BY_ID: `${BASE_URL_DOCKER}/${ENDPOINTS.DELETE_POST_BY_ID}`,
  TOGGLE_POST_HIDDEN: `${BASE_URL_DOCKER}/${ENDPOINTS.TOGGLE_POST_HIDDEN}`,
  TOGGLE_USER_FOR_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.TOGGLE_USER_FOR_POST}`,

  //USERS
  GET_ALL_USERS: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_ALL_USERS}`,

  //AUTH
  LOGIN: `${BASE_URL_DOCKER}/${ENDPOINTS.LOGIN}`,
  REGISTER: `${BASE_URL_DOCKER}/${ENDPOINTS.REGISTER}`,
  HUB: `${BASE_URL_DOCKER}/${ENDPOINTS.HUB}`,
};

let ENDPOINT_URLS;

switch (process.env.NODE_ENV) {
  case "development":
    ENDPOINT_URLS = developmentEndpoints;
    break;

  case "docker":
    ENDPOINT_URLS = dockerEndpoints;
    break;

  default:
    break;
}

export default ENDPOINT_URLS;
