const BASE_URL_DEVELOPMENT = "http://localhost:7171";
const BASE_URL_DOCKER = "http://localhost:7171";
const ENDPOINTS = {
  // POSTS
  GET_ALL_POSTS: "getAllPosts",
  GET_POST_BY_ID: "getPost",
  GET_POST_AUTHOR: "getPostAuthor",
  CREATE_POST: "createPost",
  UPDATE_POST: "updatePost",
  DELETE_POST_BY_ID: "deletePost",
  TOGGLE_POST_HIDDEN: "togglePostVisibility",
  TOGGLE_USER_FOR_POST: "toggleUserForPost",

  // USERS
  GET_ALL_USERS: "getAllUsers",
  GET_OTHER_USERS: "getOtherUsers",
  GET_USER_BY_ID: "getUser",
  GET_ADMIN_DASHBOARD: "getAdminDashboard",
  DELETE_USER: "deleteUser",
  ADD_ROLE_TO_USER: "addRoleToUser",
  REMOVE_ROLE_FROM_USER: "removeRoleFromUser",

  // AUTH
  LOGIN: "login",
  REGISTER: "register",
  POST_HUB: "postHub",
  MESSAGE_HUB: "messageHub",

  // MESSAGING
  START_CHAT: "startChat",
};

const developmentEndpoints = {
  // POSTS
  GET_ALL_POSTS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POSTS}`,
  GET_POST_BY_ID: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
  GET_POST_AUTHOR: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_AUTHOR}`,
  CREATE_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
  UPDATE_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
  DELETE_POST_BY_ID: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`,
  TOGGLE_POST_HIDDEN: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.TOGGLE_POST_HIDDEN}`,
  TOGGLE_USER_FOR_POST: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.TOGGLE_USER_FOR_POST}`,

  // USERS
  GET_ALL_USERS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
  GET_OTHER_USERS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_OTHER_USERS}`,
  GET_USER_BY_ID: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
  GET_ADMIN_DASHBOARD: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ADMIN_DASHBOARD}`,
  DELETE_USER: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER}`,
  ADD_ROLE_TO_USER: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.ADD_ROLE_TO_USER}`,
  REMOVE_ROLE_FROM_USER: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.REMOVE_ROLE_FROM_USER}`,

  // AUTH
  LOGIN: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
  REGISTER: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER}`,
  POST_HUB: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.POST_HUB}`,
  MESSAGE_HUB: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.MESSAGE_HUB}`,

  // MESSAGING
  START_CHAT: `${BASE_URL_DOCKER}/${ENDPOINTS.START_CHAT}`,
};

const dockerEndpoints = {
  // POSTS
  GET_ALL_POSTS: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_ALL_POSTS}`,
  GET_POST_BY_ID: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_POST_BY_ID}`,
  GET_POST_AUTHOR: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_POST_AUTHOR}`,
  CREATE_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.CREATE_POST}`,
  UPDATE_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.UPDATE_POST}`,
  DELETE_POST_BY_ID: `${BASE_URL_DOCKER}/${ENDPOINTS.DELETE_POST_BY_ID}`,
  TOGGLE_POST_HIDDEN: `${BASE_URL_DOCKER}/${ENDPOINTS.TOGGLE_POST_HIDDEN}`,
  TOGGLE_USER_FOR_POST: `${BASE_URL_DOCKER}/${ENDPOINTS.TOGGLE_USER_FOR_POST}`,

  // USERS
  GET_ALL_USERS: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_ALL_USERS}`,
  GET_OTHER_USERS: `${BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_OTHER_USERS}`,
  GET_USER_BY_ID: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_USER_BY_ID}`,
  GET_ADMIN_DASHBOARD: `${BASE_URL_DOCKER}/${ENDPOINTS.GET_ADMIN_DASHBOARD}`,
  DELETE_USER: `${BASE_URL_DOCKER}/${ENDPOINTS.DELETE_USER}`,
  ADD_ROLE_TO_USER: `${BASE_URL_DOCKER}/${ENDPOINTS.ADD_ROLE_TO_USER}`,
  REMOVE_ROLE_FROM_USER: `${BASE_URL_DOCKER}/${ENDPOINTS.REMOVE_ROLE_FROM_USER}`,

  // AUTH
  LOGIN: `${BASE_URL_DOCKER}/${ENDPOINTS.LOGIN}`,
  REGISTER: `${BASE_URL_DOCKER}/${ENDPOINTS.REGISTER}`,
  POST_HUB: `${BASE_URL_DOCKER}/${ENDPOINTS.POST_HUB}`,
  MESSAGE_HUB: `${BASE_URL_DOCKER}/${ENDPOINTS.MESSAGE_HUB}`,

  // MESSAGING
  START_CHAT: `${BASE_URL_DOCKER}/${ENDPOINTS.START_CHAT}`,
};

let ENDPOINT_URLS;

switch (process.env.NODE_ENV) {
  case "development":
    ENDPOINT_URLS = developmentEndpoints;
    break;

  case "docker":
    ENDPOINT_URLS = dockerEndpoints;
    break;

  default:
    break;
}

export default ENDPOINT_URLS;
