name: PostsByMarko.Client Workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DB_USER: postsbymarko
  DB_PASSWORD: posts-by-marko-ci-tests-only
  SQL_PORT: 3306
  HOST_PORT: 7171
  CLIENT_PORT: 3000
  JWT_SECRET: posts-by-marko-ci-e2e-tests-only-signing-key

jobs:
  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore ./test/PostsByMarko.FrontendTests
    
    - name: Build
      run: dotnet build ./test/PostsByMarko.FrontendTests
    
    - name: Ensure browsers are installed
      run: pwsh ./test/PostsByMarko.FrontendTests/bin/Debug/net9.0/playwright.ps1 install --with-deps  

    - name: Run frontend tests
      run: dotnet test ./test/PostsByMarko.FrontendTests
