name: PostsByMarko.Client Workflow

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  SQL_PORT: ${{ vars.SQL_PORT }}
  HOST_PORT: ${{ vars.HOST_PORT }}
  CLIENT_PORT: ${{ vars.CLIENT_PORT }}

jobs:
  run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore ./test/PostsByMarko.FrontendTests
    
    - name: Build
      run: dotnet build ./test/PostsByMarko.FrontendTests
    
    - name: Ensure browsers are installed
      run: pwsh ./test/PostsByMarko.FrontendTests/bin/Debug/net9.0/playwright.ps1 install --with-deps  

    - name: Run frontend tests
      run: dotnet test ./test/PostsByMarko.FrontendTests